export const FETCHING_POKEMON_LIST = 'FETCHING_POKEMON_LIST';
export const RECEIVED_POKEMON_LIST = 'RECEIVED_POKEMON_LIST';
export const FETCH_POKEMON_LIST_ERROR = 'FETCH_POKEMON_LIST_ERROR';

export const FETCHING_POKEMON_DETAILS = 'FETCHING_POKEMON_DETAILS';
export const RECEIVED_POKEMON_DETAILS = 'RECEIVED_POKEMON_DETAILS';
export const FETCH_POKEMON_DETAILS_ERROR = 'FETCH_POKEMONDETAILS_ERROR';
